version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    # Check the npm registry for updates every day (weekdays)
    schedule:
      interval: "daily"
    reviewers:
      - "chordjs/developer"

  - package-ecosystem: "npm"
    directory: "/packages/core"
    schedule:
      interval: "daily"
    reviewers:
      - "chordjs/developer"
