version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "daily"
    reviewers:
      - "chordjs/developer"

  - package-ecosystem: "npm"
    directory: "/packages/cluster"
    schedule:
      interval: "daily"
    reviewers:
      - "chordjs/developer"

  - package-ecosystem: "npm"
    directory: "/packages/rest"
    schedule:
      interval: "daily"
    reviewers:
      - "chordjs/developer"

  - package-ecosystem: "npm"
    directory: "/packages/sharding"
    schedule:
      interval: "daily"
    reviewers:
      - "chordjs/developer"
      
  - package-ecosystem: "npm"
    directory: "/packages/ws"
    schedule:
      interval: "daily"
    reviewers:
      - "chordjs/developer"